host: 0.0.0.0
port: 8080
subdomains: flat

admin:
  host: 0.0.0.0
  port: 6060

couchdb:
  url: http://cozy:cozy@couchdb:5984/

fs:
  url: file:///var/lib/cozy

jobs:
  workers:
    log:
      concurrency: 4

log:
  level: info
